// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADrctTeIIcvdE4mQpKEns_QC0UZssZpw4',
    appId: '1:912280112700:web:8a9a8071d055308d4d3d39',
    messagingSenderId: '912280112700',
    projectId: 'hsound-4c7c4',
    authDomain: 'hsound-4c7c4.firebaseapp.com',
    storageBucket: 'hsound-4c7c4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApp8rs1LRkyrJaCL9J2jHrSuuVK_H6LZc',
    appId: '1:912280112700:android:03c0be00185a24e74d3d39',
    messagingSenderId: '912280112700',
    projectId: 'hsound-4c7c4',
    storageBucket: 'hsound-4c7c4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANKJ88qB_kdGD-ErtmVXwaF3M2an5Lml8',
    appId: '1:912280112700:ios:77fb198573f4a5134d3d39',
    messagingSenderId: '912280112700',
    projectId: 'hsound-4c7c4',
    storageBucket: 'hsound-4c7c4.firebasestorage.app',
    iosBundleId: 'com.example.proyectoSpotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANKJ88qB_kdGD-ErtmVXwaF3M2an5Lml8',
    appId: '1:912280112700:ios:77fb198573f4a5134d3d39',
    messagingSenderId: '912280112700',
    projectId: 'hsound-4c7c4',
    storageBucket: 'hsound-4c7c4.firebasestorage.app',
    iosBundleId: 'com.example.proyectoSpotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADrctTeIIcvdE4mQpKEns_QC0UZssZpw4',
    appId: '1:912280112700:web:68e3b99e8867c88a4d3d39',
    messagingSenderId: '912280112700',
    projectId: 'hsound-4c7c4',
    authDomain: 'hsound-4c7c4.firebaseapp.com',
    storageBucket: 'hsound-4c7c4.firebasestorage.app',
  );
}
