import 'models.dart';

/// Tipo de agrupación que produjo la playlist regional.
enum RegionalPlaylistType { genre, region }

/// Playlist generada automáticamente agrupando tracks por género o región.
///
/// No se persiste; se reconstruye en runtime cada vez que el catálogo cambia.
/// Para reusar la pantalla de detalle existente, [toPlaylist] convierte
/// esta entidad a un [Playlist] estándar.
class RegionalPlaylist {
  /// Identificador sintético estable, ej. `regional_genre_son_jarocho`.
  final String id;

  /// Nombre visible (ej. "Son Jarocho", "Oaxaca Mix").
  final String name;

  /// Tipo de agrupación que la generó.
  final RegionalPlaylistType type;

  /// Tracks que pertenecen al grupo.
  final List<Track> tracks;

  /// Portada explícita. Si es `null`, se infiere de la primera pista.
  final String? coverUrl;

  /// Marca para distinguir generación automática de futuras curadurías manuales.
  final bool isAutoGenerated;

  RegionalPlaylist({
    required this.id,
    required this.name,
    required this.type,
    required this.tracks,
    this.coverUrl,
    this.isAutoGenerated = true,
  });

  /// Convierte la playlist regional a un [Playlist] estándar para
  /// reutilizar la pantalla de detalle existente.
  Playlist toPlaylist() {
    return Playlist(
      id: id,
      name: name,
      tracks: tracks,
      coverUrl: coverUrl ?? (tracks.isNotEmpty ? tracks.first.coverUrl : ''),
    );
  }

  /// Construye un slug estable y URL-safe a partir de un nombre.
  static String slugify(String input) {
    final lower = input.toLowerCase();
    return lower.replaceAll(RegExp(r'[^a-z0-9]+'), '_').replaceAll(
          RegExp(r'^_+|_+$'),
          '',
        );
  }
}
